services:
  mysql:
    image: mysql:8.0
    container_name: train-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: trainreservation
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-proot123"]
      interval: 10s
      timeout: 5s
      retries: 12

  app:
    build: .
    image: train-reservation:latest
    container_name: train-app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/trainreservation?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123
    ports:
      - "8081:8081"

volumes:
  dbdata:
